### ISSUE TITLE
Player logging out then back in loses pack.

### ISSUE THREAD

**Issue by IanLulz** [Phoenix616/ResourcepacksPlugins#10]
Hi! Not sure if this is an issue or I am doing something wrong, but at the moment it appears when a player logs out from a world with a custom resource pack they lose it. Upon logging back in, the pack doesn't load properly and it uses the default minecraft textures. The only way to get it to reload is if I make them use a different pack then switch it back, or go to a world with a different resource pack then come back. Any help would be greatly appreciated. Thanks!

**Comment by Phoenix616** [comment]
Please provide more information like your config and the log in debug mode.

**Comment by IanLulz** [comment]
Sure. Here's my config:
> debug: true
autogeneratehashes: true
messages:
  usepack: You now use the pack %pack%!
  packlisthead: 'Packs available to you:'
  nopacks: No packs found!
packs:
  potterpack:
    url: https://cdn.fadehost.com/packs/dba6a5b0098e6f736815a755b005fe9b4e3ea1b0.zip
    format: 3
    hash: dba6a5b0098e6f736815a755b005fe9b4e3ea1b0
    restricted: false
    permission: worldresourcepacks.pack.potterpack
  worldpack:
    url: https://cdn.fadehost.com/packs/b27bb01438f382926f600a64ebcd402cdec95e8a.zip
    format: 3
    hash: b27bb01438f382926f600a64ebcd402cdec95e8a
    restricted: false
    permission: worldresourcepacks.pack.worldpack
empty: worldpack
worlds:
  potterworld:
    pack: potterpack

When a the player joins the server, the console logs: 
> [WorldResourcepacks] Send pack potterpack https://cdn.fadehost.com/packs/dba6a5b0098e6f736815a755b005fe9b4e3ea1b0.zip) to Xylopod

When logging on, the pack activates in the "loading terrain" screen but it disappears when you get into the world.

**Comment by Phoenix616** [comment]
Well if it isn't printing a message that it sets it back to empty again we can at least be sure that the plugin itself isn't resetting it.

Maybe try setting the `send-delay` option in the world (or the server) section to a value above zero. (It's set to 10 ticks in the default config)

**Comment by IanLulz** [comment]
Thank you so much! That worked.

**Comment by IanLulz** [comment]
This solution works, but the value for the delay has to be rather high. What worked for me was 60 ticks (or roughly 3 seconds). Is there an issue which causes the resource pack to be handled improperly if the game is not given the 3 seconds?

**Comment by Phoenix616** [comment]
It really depends on how fast your client is able to load and render the world. Packs will only be accepted by the client after the render is finished but the server wont really know when this happened.
