### ISSUE TITLE
Resoucepack not downloading on server?

### ISSUE THREAD

**Issue by Swigglez** [Phoenix616/ResourcepacksPlugins#12]
So I have been testing this plugin for a while and it really is amazing because it completely works on my dev server but then when I plug it into my normal server nothing works or downloads?

I have been trying for days to figure this damn bug out and I am so lost because I literally have copied and pasted the config from my dev server to my normal as well as versions of the plugin so it should work?

There are no errors in console either so it's annoying me even more because I don't even know what the issue is with my main server.

Here is the config of my normal server (the broken one) - https://pastebin.com/Dzne3i6D
Here is the config of my dev server (the working one) - https://pastebin.com/QhHMbKLv

If you need me to send anything else just ask, I just wish it would work

**Comment by Phoenix616** [comment]
Please also provide your log from when the plugin starts up and when you expect it to send the pack from your normal, broken server.

**Comment by Swigglez** [comment]
https://pastebin.com/9KjrkWkR - normal server on startup
https://pastebin.com/HTDsPnyC - normal server on player join

https://pastebin.com/ZpjGEmcH - Dev server on startup
https://pastebin.com/nxgu8mkj - Dev server on player join

Sorry for the messy start up log on my normal server we have alot of plugins :/

**Comment by Swigglez** [comment]
@Phoenix616

**Comment by Phoenix616** [comment]
Did you accept the pack for your normal server in your client? Take a look at your server list entry to see if you maybe rejected it before. (here's a short guide on how to manually [accept server resource packs](https://moep.tv/minecraft/rp))

If that is not the issue then I suggest trying out the latest [development builds](https://ci.minebench.de/job/ResourcepacksPlugins/). I doubt anything about that was changed (as the pack clearly gets sent) but maybe I forgot a change in the last ~30 builds.

**Comment by Swigglez** [comment]
this fixed it thank you so much!
