### ISSUE TITLE
Slow world switches?

### ISSUE THREAD

**Issue by SlimeDog** [Phoenix616/ResourcepacksPlugins#19]
Spigot 1.13.1 latest
WRP 1.6.19-b224
MV-Core 2.6.0-b738

Changing worlds seems quite a bit slower in 1.13.x than in 1.12.2, like from near instantaneous to over 10 seconds. Am I the only one with this experience, or is this a known issue? Assuming the latter, is it related to resourcepack loading? Is there anything to be done? I don't think the fault lies with WRP, but I don't know where else to ask.

My packs are approximately 30-72KB. Most of my worlds use a single pack, but even moving between those worlds takes much longer than in 1.12.2. I appreciate that MC loads the entire default pack every time, then compares/replaces anything provided by my packs.

**Comment by Phoenix616** [comment]
Unfortunately that is not something that a plugin could change as it is entirely up to the client how long it takes to either apply resource packs or load the world on switch in general.

The only thing I can suggest that you could take a look at is the client's log, there could be errors in the pack that slow down the loading process or something like that.

**Comment by SlimeDog** [comment]
As expected. Thanks.

No errors. It's just s...l...o...w. And I have a pretty fast client machine.  :)
