### ISSUE TITLE
Error while trying to get the UserConnection field from the DownstreamBridge object.

### ISSUE THREAD

**Issue by mibby** [Phoenix616/ResourcepacksPlugins#26]
Waterfall dev 278
BungeeResourcePacks dev 269

@Phoenix616 I seem to be noticing this error in my Waterfall logs when players try connecting and get disconnected.

```
[13:26:02] [Netty Worker IO Thread #3/ERROR] [BungeeResourcepacks]: Error while trying to get the UserConnection field from the DownstreamBridge object. Is the plugin up to date?
```

**Comment by Phoenix616** [comment]
Well that's Waterfall, not BungeeCord. The plugin gets build with the latest BungeeCord internals not Waterfall so any change which Waterfall might make (like changing the 1.14 protocol version) will most likely break it.
