### ISSUE TITLE
How would I configure WorldResourcePack to only listen for the relay of BungeeResourcePack?

### ISSUE THREAD

**Issue by mibby** [Phoenix616/ResourcepacksPlugins#27]
Waterfall dev 294
BungeeResourcePack dev 280
Paper dev 186 (Spigot 1.14.4)
WorldResourcePack dev 280

@Phoenix616 How would I configure WorldResourcePack so it does not modify the resource pack loading at all but listens for BungeeResourcePack for relaying to ShowItem - to prevent chinese characters from showing if not using the resource pack?

BRP Config
https://paste.ubuntu.com/p/TVw5sfyxD2/
WRP Config
https://paste.ubuntu.com/p/PjRJKpN6W4/

If WRP is configured with a pack, the resource pack gets sent / loads twice on login. It also forces the pack to load again if you idle connections on the proxy and reconnect clients back to the server after a restart, even if it's set to use the same pack.

If WRP is not configured with a pack, the resource pack only gets sent once by BRP and the pack doesn't force load again if you idle connections on the proxy and reconnect it to the server after a restart. However if you change worlds while in-game, WRP forces the pack to change to Empty!

I would just like BungeeResourcePack to control global loading of the pack but communicate to WorldResourcePack so it can tell ShowItem to not show chinese characters to players not using the resource pack. It seems like they don't currently communicate to each other and each independently try to load a resource pack. :(

**Comment by Phoenix616** [comment]
You should be able to just set the pack as a secondary one in WorldResourcepacks and it shouldn't send the pack twice anymore nor reset on world change.

**Comment by mibby** [comment]
@Phoenix616 Unfortunately that doesn't seem to be the case. 

I made the following changes to WRP.
https://paste.ubuntu.com/p/zMM5nKKzj9/

However it is still occasionally forcing resource packs to load when changing worlds.

**Comment by Phoenix616** [comment]
Cell the config looks correct. Could you provide the debug log from both
the Bukkit and the Bungee side when that happens?

**Comment by mibby** [comment]
I'll have to debug when I find some spare time. However it definitely seems related to BRP having the empty pack configured as a secondary. Since setting the pack as primary and secondary in BRP and only secondary in WRP, I have not heard this issue occurring again.
