### ISSUE TITLE
Server icon not displaying.

### ISSUE THREAD

**Issue by mibby** [Phoenix616/ResourcepacksPlugins#29]
Paper dev 213 (Spigot 1.14.4)
Travertine dev 109 (BungeeCord)
BungeeResourcePack dev 280

Is it not possible to display the server resource pack icon when loading a server pack? The icon is 64x64 and png, displays fine when loading the pack zip manually. Just when the resource pack is forced loaded by the server, there is no icon.

![link](https://i.imgur.com/nHRtG40.png)

**Comment by Phoenix616** [comment]
Unfortunately that seems to be a limitation of the Vanilla client.

**Comment by mibby** [comment]
That's a bummer. :(
