### ISSUE TITLE
Resource pack update does not download and use the newer version on first login of new update.

### ISSUE THREAD

**Issue by mibby** [Phoenix616/ResourcepacksPlugins#30]
Not sure if this is a bug or just a vanilla issue but if you push a resource pack update and regenerate hashes with BungeeResourcePack, when someone logs in for the first time since the update, it does not download and enable the pack.

Client logs seem to detect the mismatched server pack and deletes the local server pack, but does not re-download and enable. Relogging again, the pack re-downloads and enables.

**Comment by Phoenix616** [comment]
Could you please also provide the plugin, client and server versions that you are using when this happens?

**Comment by mibby** [comment]
Paper dev 221 (Spigot 1.14.4)
Travertine dev 109 (Waterfall/BungeeCord fork)
BungeeResourcePack dev 280

Client is 1.14.4. I do have ViaVersion/ViaBackwards/ViaRewind installed too to allow older versions to connect, but it seems to happen without as well.

**Comment by mibby** [comment]
@Phoenix616 Is there anything I can do to help you debug this? It's a bit silly that players have to relog twice to get the updated resource pack to download / enable if they have an older version. :(

**Comment by Phoenix616** [comment]
The client's latest log should include information about why it isn't applying the pack the first time. Also the plugin's debug log messages might be helpful.

**Comment by mibby** [comment]
Apologies for getting back to this issue so late. Upon further testing, this just seems to be how the vanilla client handles things. I tested with various other resource pack plugins and regardless of what goes on, if the hash does not match, the client does not re-attempt a new download on the same check instance. You have to relog to force it to re-download an updated pack.

Login > Mismatched Hash > Deletes Local Server Pack > Doesn't attempt a re-download
Login > No Local Server Pack > Downloads Pack > Enables Pack
Login > Hash Matches > Enables Pack

In which case, would it be possible to add a command to re-send the download/use request to the client if it doesn't enable?

**Comment by Phoenix616** [comment]
Interesting, I thought they fixed that. And you are running the latest
client version, right?

Regarding the command: That could be doe with /usepack already but I guess
you mean like a dedicated one that just resends the pack the player should
have applied?

**Comment by mibby** [comment]
I am running on 1.15.1, yes. However first noticed this being a problem with 1.14. Perhaps may have been present in 1.13 as well.

> I guess you mean like a dedicated one that just resends the pack the player should
have applied?

Yep. Otherwise players would have to know and type the name of the pack. Would typing /usepack even re-send the load packets if you are already on that pack?

**Comment by mibby** [comment]
Would forcing a resend twice if a new version is detected be possible to work around the issue?

**Comment by Phoenix616** [comment]
Maybe but it should just replace the local one if it doesn't match. If it doesn't I suggest opening an issue with Mojang.

**Comment by mibby** [comment]
I'm a bit weary about reporting bugs to the MC issue tracker due to possible duplicate reporting. I came across these two issues that might be related, but I'm not sure if it is a high priority fix for Mojang since they were reported during 1.14 time as well.

https://bugs.mojang.com/browse/MC-164316
https://bugs.mojang.com/browse/MC-165927

**Comment by Phoenix616** [comment]
Workaround for the Vanilla bug has been added a while ago with the `append-hash-to-url` option.
