### ISSUE TITLE
Players dont automatically get packs when loading server

### ISSUE THREAD

**Issue by PeaceDealer** [Phoenix616/ResourcepacksPlugins#31]
Hi,

I've tried setting up your plugin, but I can't get the pack to apply when people switch server?

Config:
```
debug: true
default-language: en
disable-metrics: false
autogeneratehashes: true
usepack-is-temporary: true
stored-packs-override-assignments: false
permanent-pack-remove-time: 30
packs:
  mech:
    url: https://gamingculture.xyz/download/MechResources_v2.2.0.zip
    hash: ee8bfd399da3a065ec5426e287f701d8a020ca28
    format: 5
    restricted: false
global:
  send-delay: 20
servers:
  survival-chill:
    pack: mech
```

So, nothing essentially happens when a user joins the `survival-chill` server.
But if I from the bungee console runs `usepack mech PeaceDealer` the pack does apply fine.

On join, I also see this message appear in the console:
` Backend mc server send pack backend-mechresources_v2.2.0 (http://gamingculture.xyz/download/MechResources_v2.2.0.zip) to player PeaceDealer`
and it seems as if it's trying to load it, but it's not applied.

**Comment by Phoenix616** [comment]
Please remove the pack from the backend server and test then. BungeeResourcepacks will not send the pack another time if the backend server already sent it. Also please provide your full log if that doesn't already fix it.

**Comment by PeaceDealer** [comment]
That was exactly it. Thanks!
Had even forgotten I set that up as well.
