### ISSUE TITLE
resource pack asking player to download on every join

### ISSUE THREAD

**Issue by BlackScoped** [Phoenix616/ResourcepacksPlugins#32]
how can I make the resource pack ask the player if he wants it on every join

**Comment by Phoenix616** [comment]
Not possible. The Vanilla client caches the response in the server list entry and it needs to be [edited manually](http://moep.tv/minecraft/rp).

**Comment by Phoenix616** [comment]
Starting with 1.17 this is now default Vanilla behaviour.
