### ISSUE TITLE
PerWorldResourcepack doesn't work

### ISSUE THREAD

**Issue by Chunkst** [Phoenix616/ResourcepacksPlugins#36]
Hello, it is possible to explain to you our problem on discord. Contact me at ChunkLoader#1528

**Comment by Phoenix616** [comment]
Please just explain your problem here, there is an issue system for a reason.

**Comment by ChunkLoader** [comment]
In fact I tried your plugin, another similar one, a piece of code I created and even via server.properties and I can't get anything to work, sometimes it downloads something and sometimes it doesn't but it never applies my resourcepack while I even tried with a Faithful basic. For the links it's an autodownload dropbox so normally no worries ...

**Comment by Phoenix616** [comment]
Please use your own web host (without cloudflare or similar checking) or try [mc-packs.net](https://mc-packs.net/), Dropbox is known to sometimes cause issues lately.

**Comment by ChunkLoader** [comment]
Thank you very much this site works very well my resource pack finally works in server.properties. As for my own hosting I have a mineweb site but no idea how to make an automatic download. Good with mcpacks it seems to work. Thank you very much very good plugin.

Just a little problem : when I join the specific world I get the resource pack but when I leave it I freeze (normal) then I'm ejected from the server ...

**Comment by Phoenix616** [comment]
You'll have to take a look at why you are disconnecting in your server and client log.

**Comment by ChunkLoader** [comment]
Well, I'm out, and so is one of my employees. However, another one works very well for him, so I'll keep you posted.
