### ISSUE TITLE
BadPacket ID, are mods in use!? - BungeeCord incompatibility

### ISSUE THREAD

**Issue by linsaftw** [Phoenix616/ResourcepacksPlugins#41]
Hi, your plugin is causing this error on BungeeCord:

[HyperTv] <-> DownstreamBridge <-> [lobby-1] - bad packet ID, are mods in use!? Did not read all bytes from packet class de.themoep.resourcepacksplugin.bungee.packets.ResourcePackSendPacket 58 Protocol GAME Direction TO_CLIENT

(I am not having this issue because i don't use your plugin, this was reported by another person and i reported it for him)

**Comment by Phoenix616** [comment]
Please provide the version of the plugin and bungeecord as well as the one of the back-end Minecraft server.
