### ISSUE TITLE
Regex in config?

### ISSUE THREAD

**Issue by fiftywalrus** [Phoenix616/ResourcepacksPlugins#43]
Hello, I'm using a custom plugin to generate dungeons and the world name is different for each instance of a dungeon.

I noticed there is a regex: option in the config, but couldn't find any documentation on what it does. Is it possible that it allow for a resource pack to be used on a specific set of worlds that fit the regex?

Best,
Kalvin

**Comment by Phoenix616** [comment]
You simply define the regex in the [`regex` option](https://docs.saltstack.com/en/latest/topics/yaml/#rule-three-dashes) in the world assignment. If that is defined then the assignment name will not be used as a literal world name.
