### ISSUE TITLE
Can I add multiple Resourcepack in the same world?

### ISSUE THREAD

**Issue by Fede2782** [Phoenix616/ResourcepacksPlugins#51]
Can I add multiple resourcepacks in the same world?
Plugin version: 1.8.2

**Comment by Phoenix616** [comment]
If you mean multiple packs at the same time then no, the Vanilla Minecraft client can only have one server resource pack applied at the time. If you want the resources of multiple packs then you are going to have to merge them into one zip file.

If you mean different packs in different locations then that is possible with the premium version of the plugin ([ForceResourcepacks](https://frp.phoenix616.dev)) via WorldGuard region flags.

**Comment by Fede2782** [comment]
Thank you.
