### ISSUE TITLE
Java errors while starting my server on Velocity

### ISSUE THREAD

**Issue by x9nico** [Phoenix616/ResourcepacksPlugins#53]
Hello, I have these errors when my server start => https://pastebin.com/qiDNbxSX

**Comment by Phoenix616** [comment]
Please provide the missing information which is requested in the [issue template](https://github.com/Phoenix616/.github/blob/master/.github/ISSUE_TEMPLATE/bug-report.md) (Especially your used versions)

**Comment by Phoenix616** [comment]
You are using a non-compatible version of Velocity. The plugin only runs with Velocity above 1.1.3 as mentioned in the [thread](https://forums.velocitypowered.com/t/velocityresourcepacks-manage-resourcepacks-for-servers-and-whole-proxy/515).

**Comment by Phoenix616** [comment]
You are using an old build of the plugin, please test the latest one and see if the issue persists.

**Comment by x9nico** [comment]
It works in latest dev build. Thanks !
