### ISSUE TITLE
[BungeeResourcepacks] players not getting download prompt

### ISSUE THREAD

**Issue by Tracenji** [Phoenix616/ResourcepacksPlugins#56]
hello, i am using BungeeResourcepacks on waterfall-1.17-445
the resourcepack loads with no issues if i set "server resource packs: enabled" in server info
but it does not give me a prompt to enable server resource pack if i have it set to "server resource packs: prompt"

version is 1.17
here is my config (with links and pack names edited)

> debug: true
default-language: en
disable-metrics: false
autogeneratehashes: true
usepack-is-temporary: false
stored-packs-override-assignments: true
permanent-pack-remove-time: 30
empty:
  url: http://cdn.moep.tv/files/Empty.zip
  hash: 01517226212d27586ea0c5d6aff1aa5492dd2484
global:
  pack: packname1
servers:
  BirbServer:
    pack: packname1
    secondary:
    - gamepack
  BetterServer:
    pack: packname1
    regex: minigame_.*
packs:
  packname1:
    url: https://link.link/pack.zip
    hash: 1d2057e39ce8a73c1c0a8b16fdc0f9b492640725
    format: 7
    version: '1.17'
    restricted: false
    permission: bungeeresourcepacks.pack.packname1
  ores:
    url: hhttps://link.link/pack.zip
    hash: 1d2057e39ce8a73c1c0a8b16fdc0f9b492640725
    format: 7
    version: '1.17'
    restricted: false
    permission: bungeeresourcepacks.pack.packname1
  globalpack:
    url: http://example.com/globalpack.zip
    hash: abcdef012345678abcdef012345678abcdef0123
    restricted: false
    permission: bungeeresourcepacks.pack.globalpack
  gamepack:
    restricted: false
    permission: bungeeresourcepacks.pack.gamepack
    variants:
    - url: http://example.com/minigameresourcepack_1_15.zip
      hash: 012345678abcdef012345678abcdef012345678a
      format: null
      version: '1.15'
      restricted: false
      permission: bungeeresourcepacks.pack.gamepack-variant-1
      type: null
      variants: null
    - url: http://example.com/minigameresourcepack_1_12.zip
      hash: 012345678abcdef01234567dddcdef012345678a
      format: null
      version: '1.12'
      restricted: false
      permission: bungeeresourcepacks.pack.gamepack-variant-2
      type: null
      variants: null

here is bungee console
![image](https://user-images.githubusercontent.com/28219016/126741371-66beb377-4068-435e-b49f-bcdaac8aac22.png)

**Comment by Phoenix616** [comment]
Common issue with slow PCs/internet, try increasing the `send-delay` option. Also make sure no teleport or inventory open happens when the pack is sent.
