### ISSUE TITLE
The plugin doesn't even attempt to load resource packs when changing worlds.

### ISSUE THREAD

**Issue by VirgilGunder** [Phoenix616/ResourcepacksPlugins#60]
#### Used Version
Version: 1.8.5 (build 417)
 
 
#### Config
# 
# Default language
debug: true
default-language: en
disable-metrics: false
autogeneratehashes: true
usepack-is-temporary: true
stored-packs-override-assignments: false
permanent-pack-remove-time: 30
empty:
  url: http://cdn.moep.tv/files/Empty.zip
  hash: 01517226212d27586ea0c5d6aff1aa5492dd2484
global:
  send-delay: 10
worlds:
  Arena:
    pack: pvp-arena
    regex: Arena_.*
packs:
  pvp-arena:
    url: https://download.mc-packs.net/pack/a45ee72bca40951f80b7af4a45e3b4d3ac37738d.zip
    restricted: false
    permission: resourcepacksplugin.pack.pvp-arena
 

#### Environment description
Using the multiverse plugin and advanced teleport
 
 
#### Full Log
https://bin.bloom.host/lezejijonu

#### What is happening?
When I go to the world called Arena nothing happens, no packs try to load or anything and the config is totally correct as far as I can see.

#### What did you expect to happen?
I expected the pack pvp-arena to load

**Comment by Phoenix616** [comment]
Two things:

- You are running an ocd buld which is incompatible with your server version as the startup error tells you. Update.
- Your config is setup to match worlds starting with `Arena_` while your world is named `Arena`. Either adjust your regex to match it or completely remove the regex option to match the assignment name literally.

**Comment by VirgilGunder** [comment]
Thanks
But is there even a version for 1.17.1? I haven’t been able to find it.

**Comment by VirgilGunder** [comment]
Sorry misclicked

**Comment by Phoenix616** [comment]
The readme contains the link to the latest dev builds.

**Comment by VirgilGunder** [comment]
The server keeps downloading the resource pack even in wrong worlds now, any idea why?
When I'm in the default world it downloads the one for Arena

**Comment by VirgilGunder** [comment]
Now its working but how do i make the game take off the resource pack when you leave the world?

**Comment by Phoenix616** [comment]
That is done automatically with the empty pack.
