### ISSUE TITLE
1.17.1+ Required Resource Pack for Velocity

### ISSUE THREAD

**Issue by OverBrave** [Phoenix616/ResourcepacksPlugins#67]
Yes I know. This Premium plugin is available, but a feature that exists in Minecraft must not be paid for a proxy server.

Can't you at least add this feature for Proxy (BungeeCord and Velocity)?

I would love to buy your plugin and support you, but I don't want to buy it just for this feature.
And due to the geography I live in, the price is too high for me.

I would be very grateful if you could bring this feature.

**Comment by Phoenix616** [comment]
As you have already correctly deduced that functionality is available in ForceResourcepacks and will therefore not be added to this plugin. Feel free to either use ForceResourcepacks under the terms of its license (GPLv3), to add that functionality to your own fork of this plugin, use the Minecraft server functionality directly or use some other plugin offering that functionality.
