### ISSUE TITLE
Command to see if a player uses one of the Bungee Resourcepacks

### ISSUE THREAD

**Issue by RedstoneFuture** [Phoenix616/ResourcepacksPlugins#70]
#### Is your feature request related to a problem? Please describe.
If you do not force the resource packs, the support team can use it to verify that the player has installed the optional pack. This way, it can be determined if the player has a technical problem or simply forgot about the RP.

#### Describe the solution you'd like
`/brp list <player>` = List all RPs that the player currently has activated. It checks only the resourcepacks controlled by the plugin "Bungee Resourcepacks" or "World Resourcepacks".

#### Describe alternatives you've considered
Of course, you can explain to the player where to view the resourcepacks by self. But it all might take a little longer and can't be controlled directly by the support.

#### Additional context
At events, it must go fast, so a command is the fastest way to help the player here.

**Comment by Phoenix616** [comment]
This is already a feature in ForceResourcepacks (`/frp getpack <user>`, see [its docs](https://www.spigotmc.org/resources/force-resourcepacks.10499/field?field=documentation)) which also takes into account if the user accepted or rejected the pack.
