### ISSUE TITLE
Make it Compatible With GeyserMC

### ISSUE THREAD

**Issue by BobtheBob123456** [Phoenix616/ResourcepacksPlugins#71]
Basically how it soueach.

 Make it so that bedrock players are exempt from the resource packs if they are forced, and/or making it possible for bedrock players to be sent their own resource packs for each world.

**Comment by BobtheBob123456** [comment]
Never mind. I see this has already been discussed.

**Comment by Phoenix616** [comment]
Duplicate of #58
