### ISSUE TITLE
I cant get it to work no popups no nothing

### ISSUE THREAD

**Issue by Wolf195** [Phoenix616/ResourcepacksPlugins#72]
### **Plugin Version:** 
1.8.5
### **Minecraft Server Version:** 
Spigot 1.15.2
--------------------------------------------------------------------------------------------------------------------------
**Config:**

debug: true
default-language: en
disable-metrics: false
autogeneratehashes: true
usepack-is-temporary: true
stored-packs-override-assignments: false
permanent-pack-remove-time: 0
empty:
  url: http://cdn.moep.tv/files/Empty.zip
  hash: 01517226212d27586ea0c5d6aff1aa5492dd2484
worlds:
  world:
    pack: Test
packs:
  Test:
    url: https://download.mc-packs.net/pack/779aaf9898d90fe2c8c47a14e9ecd1335230ee8c.zip
    hash: 779aaf9898d90fe2c8c47a14e9ecd1335230ee8c
    format: 5
    version: "1.15.2"
    restricted: false

### **Full log:** 

https://mclo.gs/BYYisBW
--------------------------------------------------------------------------------------------------------------------------
### **Other Plugins:**

FriendsSpigot
PlaceholderAPI
pMessage
ViaVersion
ConsoleSpamFix
ProtocolLib
LuckPerms
AntiCheatReloaded
Vault
MyCommand
SuperLobby
WorldEdit
Essentials
EssentialsDiscord
NicknamerPlus
IridiumSkyblock
Multiverse-Core
Multiverse-Inventories
--------------------------------------------------------------------------------------------------------------------------
**What's happening**

I don't get any popup saying to download the pack but the console says it sent the pack to me but I don't get anything and I don't have the resource pack I made for the world called world
--------------------------------------------------------------------------------------------------------------------------
**What I expected**

I expected to download the world resource pack and see it in game

**Comment by Phoenix616** [comment]
Please make sure that you have enabled server resourcepacks in your client. (The server settings in the multiplayer list)

Also check your client's log if there are any errors loading the pack.

Finally if none of these are the issue then please test with the latest build of the plugin.
