### ISSUE TITLE
Plugin don't switch resource when i change world..

### ISSUE THREAD

**Issue by PJGamerr** [Phoenix616/ResourcepacksPlugins#73]
I use the "ForcePack" plugin to force my users to set a specific texture pack once they enter the hub and I wanted to set a different texture for a particular world (always within the Hub server), more precisely I would like it in the world "Builder" an empty texture pack is set, this is my config, what am I doing wrong?

debug: true
# Default language
default-language: en
# Disable all metrics included in this plugin.
disable-metrics: false
# Whether or not resourcepack file hashes should be generated on startup:
autogeneratehashes: true
# Whether /usepack should apply packs temporary or permanent when run without any argument:
usepack-is-temporary: true
# Whether packs that a player has stored will override a matched assignments
stored-packs-override-assignments: false
# When manually setting a permanent pack then it will be reset if the user disconnects in under x amount of seconds.
# 0 or anything below will disable this functionality
permanent-pack-remove-time: 30
packs:
  Hub: 
    url: http://resourcepack.host/dl/5Ijnh4QJeAmGElQjhR2FfQZbehGZ5X5e/1.zip
    hash: 1F8538032EAEF9664FE457E5B44DC0A2B9667B90
    format: 9
    version: "1.8"
    restricted: false
    permission: worldresourcepacks.pack.lobbypack
empty:
  url: http://cdn.moep.tv/files/Empty.zip
  hash: 01517226212d27586ea0c5d6aff1aa5492dd2484
global:
  pack: Hub
  send-delay: 10
worlds:
  Hub:
    pack: Hub
  Builder:
    pack: empty

**Comment by Phoenix616** [comment]
You don't need to specify the empty pack explicitly. The plugin will autobatically remove the pack if it sent a pack before and the user switches to a world that doesn't have one. (It doesn't support packs sent by third party plugins though, if that is your goal then you would have to use a separate pack for resetting, not the inbuilt empty one as that's a special case internally.)

The easier solution is to just use my [ForceResourcepacks plugin](https://frp.phoenix616.dev) though.
