### ISSUE TITLE
append-hash-to-url causing disconnect on login with 1.19.3.

### ISSUE THREAD

**Issue by mibby** [Phoenix616/ResourcepacksPlugins#74]
#### Used Version
BungeeResourcePack dev 487
 https://ci.minebench.de/view/All/job/ResourcepacksPlugins/
  
#### Environment description
Waterfall dev 510
https://papermc.io/downloads#Waterfall
 
Server is 1.19.2 with ViaVersion support for 1.19.3.

#### What is happening?
-snip-

#### What did you expect to happen?
Connecting and being sent the newer resource pack if the higher game version is detected.

#### Additional context
Setting ``append-hash-to-url: false`` allows 1.19.3 clients to connect again.

**Comment by Phoenix616** [comment]
The issue has nothing to do with that config option. Previously that was done automatically, the option just allows disabling that feature.

The error shows if a wrong packet is sent to the client, please make sure that you are actually running build 487 when you test this. You can also try adjusting your `packetmap.yml` to look [like this](https://github.com/Phoenix616/ResourcepacksPlugins/blob/master/bungee/src/main/resources/packetmap.yml) but that shouldn't normally be necessary to do manually. (The log should also say whether or not it properly registers the 1.19.3 packet)

**Comment by Phoenix616** [comment]
> That's odd. My `packetmap.yml` didn't have anything for 1.19 in it. Re-adding the defaults from what you linked and enabling the setting, everything seems fine now. Thanks!

Well it shouldn't need to have it in it. It should load the missing ones from the jar file itself so it's a bit odd that it didn't do that for you :S
