### ISSUE TITLE
I cant get own ranks to server

### ISSUE THREAD

**Issue by hellotuba** [Phoenix616/ResourcepacksPlugins#75]
this is my default.json for the better ranks and if i get the bungee if says: server resource pack couldnt be applied 

there is the code:

{"providers":[
	{
		"type": "bitmap",
		"file": "minecraft:hellotuba/builder.png",
		"height": 9,
		"ascent": 9,
		"chars": [
			"🅾"
		]
	},
	{
		"type": "bitmap",
		"file": "minecraft:hellotuba/helper.png",
		"height": 9,
		"ascent": 9,
		"chars": [
			"🅿"
		]
	},
	{
		"type": "bitmap",
		"file": "minecraft:hellotuba/admin.png",
		"height": 9,
		"ascent": 9,
		"chars": [
			"贝"
		]
	},
	{
		"type": "bitmap",
		"file": "minecraft:hellotuba/owner.png",
		"height": 9,
		"ascent": 9,
		"chars": [
			"德"
		]
	},
    {
	   "type":"bitmap",
	    "file":"along:hellotuba/banner.png",
	    "height":52,
	    "ascent":33,
	    "chars":["\ue001"]
    },
    {
		"type":"bitmap",
		 "file":"along:hellotuba/hlhelper.png",
		 "height":52,
		 "ascent":33,
		 "chars":["\ue002"]
	 },
	 {
		"type":"bitmap",
		 "file":"along:hellotuba/Developer.png",
		 "height":52,
		 "ascent":33,
		 "chars":["\ue003"]
	 },
	 {
		"type":"bitmap",
		 "file":"along:hellotuba/zkhelper.png",
		 "height":52,
		 "ascent":33,
		 "chars":["\ue004"]
	 },
	 {
		"type":"bitmap",
		 "file":"along:hellotuba/vedení.png",
		 "height":52,
		 "ascent":33,
		 "chars":["\ue005"]
	 },
	 {
		"type":"bitmap",
		 "file":"along:hellotuba/Technik.png",
		 "height":52,
		 "ascent":33,
		 "chars":["\ue006"]
	 },
	 {
		"type":"bitmap",
		 "file":"along:hellotuba/boxfight.png",
		 "height":52,
		 "ascent":33,
		 "chars":["\ue007"]
	 },
	 {
		"type":"bitmap",
		 "file":"along:hellotuba/survival.png",
		 "height":52,
		 "ascent":33,
		 "chars":["\ue008"]
	 }
]
}

**Comment by Phoenix616** [comment]
This is not general resourcepack support. If your pack has an error then ask in a community about resource pack creation, this issue tracker is for issues with my plugin code and functionality.
