### ISSUE TITLE
Is it possible to prevent resource usage prompt using packets?

### ISSUE THREAD

**Issue by mibby** [Phoenix616/ResourcepacksPlugins#8]
Is there any way using packets (ProtocolLib or other methods) to prevent the resource use prompt on login from appearing every time someone connects, to then instead have clients use a cached version of the server resource pack if the hash matches? As having it re-ask people to use and download the server pack every time they login to the server is quite an annoyance.

**Comment by Phoenix616** [comment]
The client should only show the prompt the first time the player logs into a server. After that the setting is cached in the server list entry. (So it wont cache when using direct connect)

Also the prompt is independent from the actual resource pack handling, the hash just stops the client from re-downloading the pack and has not influence on the prompt.

**Comment by mibby** [comment]
With my local testing on 1.11, the prompt appears every single time I login. Are you saying the ```Server Resource Packs: Prompt``` server list setting should change to enabled once accepted for the first time? As it doesn't seem to want to for me and doesn't cache the server resource pack in the resource folder.

**Comment by Phoenix616** [comment]
Yes, it changes to enabled for me and caches the pack when the hash is correctly set.

**Comment by mibby** [comment]
Hm, odd. I updated from the WorldResource version to BungeeCord and it seems to enable full time now. However, if people click no, it never prompts them again. Is it possible to force a prompt every time they login until they accept it?

**Comment by Phoenix616** [comment]
Unfortunately there is currently no way to force the prompt on each login. The player has to manually re-enable it in the settings of the server list entry.

**Comment by mibby** [comment]
Oh, that's unfortunate. :( I don't think most people would know how to do that.

What about the client stutter when connecting? Is there any way to minimize the connection lag / client freeze every time someone connects when it attempts to load the resource pack?

**Comment by Phoenix616** [comment]
The stutter is caused by the client having to reload all the resources and really depends on the performance of the user's machine.

It would be better if Minecraft could just reloaded the changed resources but currently it re-reads and applies all textures, sounds etc. from the default pack and all other applied ones.

**Comment by mibby** [comment]
Is it certain that the lag occurs on all servers that use a custom resource pack? As I'm having some users that are even crashing when logging in when it forces a load. I have some users that say they don't experience this problem on other servers that have a pack. My resource pack isn't larger than 2 MB.

**Comment by Phoenix616** [comment]
Applying a resource pack always requires the client to reload all resources, so the time it takes and the effects of the applying should be the same no matter whether it is done via the server's request or the resourcepack menu.

Regarding the crashes: I have seen these when players use textures with higher resolutions and don't have enough memory/a weak cpu to properly stitch them together/scale lower res textures up.
