### ISSUE TITLE
Support global pack loading on server join

### ISSUE THREAD

**Issue by airoons** [Phoenix616/ResourcepacksPlugins#84]
1.20.3 (and 1.20.4) has changed the way how packs defined in server.properties load - they are applied before the player has joined the server (in "joining screen").

Would it be possible to have a similar functionality if one "global" pack is used? I am looking for a Velocity solution to apply ONE global resource pack before a player has even joined the proxy.

Can you please look into this? Or have I missed a configuration option regarding this..

Thanks!

**Comment by Phoenix616** [comment]
That is not possible yet as there is no API for it but as soon as Velocity adds that I will add support for it.

**Comment by airoons** [comment]
Thanks for the quick response, is that already planned or should I suggest that somewhere in Velocity repo?

**Comment by Phoenix616** [comment]
Pretty sure that's already planed.

**Comment by airoons** [comment]
Hey @Phoenix616,

Any updates on this? Maybe I should open a feature request on velocity repo or smth.

**Comment by Phoenix616** [comment]
Not sure what kind of updates there would be? Once it is possible it will be implemented in the plugin and this issue closed.

**Comment by airoons** [comment]
Closing this as it seems to work with your ForceResourcepacks plugin.

**Comment by Phoenix616** [comment]
While it might seem like it works for you there definitely was no change in the code (nor in Velocity's API) to support that properly so I'm going to reopen this.

**Comment by Phoenix616** [comment]
This has been working in Velocity for a while now (with `send-delay: 0`), not supported on Bungee or Spigot/Paper yet hence why I'm leaving this open.
