### ISSUE TITLE
Option to disable metrics.

### ISSUE THREAD

**Issue by mibby** [Phoenix616/ResourcepacksPlugins#9]
I have bStats disabled on my BungeeCord configuration. Would it be possible to add an option to disable the check in BungeeResourcepacks as well?

```
02:39:48 [FINE] [BungeeResourcepacks] Failed to submit plugin statistics: java.io.IOException: Server returned HTTP response code: 504 for URL: http://report.mcstats.org/plugin/BungeeResourcepacks
```

**Comment by Phoenix616** [comment]
MCStats can be disabled via the normal config in the PluginMetrics folder.
